// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Ex-QFkRFSP8yfBkYvd0HhrSdAfV4dp4',
    appId: '1:838386178394:web:c5a0f82f1d56f7f472fb63',
    messagingSenderId: '838386178394',
    projectId: 'fir-flutter-codelab-3e4bb',
    authDomain: 'fir-flutter-codelab-3e4bb.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-3e4bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcJEKpWFXvI67xQPxyWK87XVQfKadqbrg',
    appId: '1:838386178394:android:87c1eb94e6535dce72fb63',
    messagingSenderId: '838386178394',
    projectId: 'fir-flutter-codelab-3e4bb',
    storageBucket: 'fir-flutter-codelab-3e4bb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMDxyY-JnT5Yvek2ce4r4CapwKDfXs3is',
    appId: '1:838386178394:ios:ff9239842934027572fb63',
    messagingSenderId: '838386178394',
    projectId: 'fir-flutter-codelab-3e4bb',
    storageBucket: 'fir-flutter-codelab-3e4bb.firebasestorage.app',
    iosClientId: '838386178394-4i4jb8o99dvhr81trmb450qb1pnue2bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMDxyY-JnT5Yvek2ce4r4CapwKDfXs3is',
    appId: '1:838386178394:ios:ff9239842934027572fb63',
    messagingSenderId: '838386178394',
    projectId: 'fir-flutter-codelab-3e4bb',
    storageBucket: 'fir-flutter-codelab-3e4bb.firebasestorage.app',
    iosClientId: '838386178394-4i4jb8o99dvhr81trmb450qb1pnue2bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Ex-QFkRFSP8yfBkYvd0HhrSdAfV4dp4',
    appId: '1:838386178394:web:addccb2865b1087b72fb63',
    messagingSenderId: '838386178394',
    projectId: 'fir-flutter-codelab-3e4bb',
    authDomain: 'fir-flutter-codelab-3e4bb.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-3e4bb.firebasestorage.app',
  );
}
